[package]
name = "span_derive"
description = "derive macro for token Span struct"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/Bangboom030518/M-Compiler"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = "1.0.102"