
<const_decl> ::= "const" <assignment>;

<assignment> ::= <identifier> "=" <expression>;

(* Words *)

<lowercase> ::= a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z;
<uppercase> ::= A|B|C|D|E|F|G|H|I|J|K|L|M|N|O|P|Q|R|S|T|U|V|W|X|Y|Z;
<identifier_char> ::= <lowercase>|<uppercase>|_;
<identifier> ::= <ident_char>|<ident><ident_char>;

(* Numbers *)

<numeric_literal> ::= <int>|<float>;
<float> ::= -<ufloat>|<ufloat>;
<ufloat> ::= <uint>.<uint>;
<int> ::= <uint>|-<uint>;
<uint> ::= <digit>|<nonzero><digits>;
<digits> ::= <digit>|<digits><digit>;
<digit> ::= 0|<nonzero>;
<nonzero> ::= 1|2|3|4|5|6|7|8|9;
