[package]
name = "parser"
version = "0.1.0"
edition = "2021"

[dependencies]
cranelift = { workspace = true }
itertools = { workspace = true }
thiserror = { workspace = true }
tokenizer = { path = "../tokenizer" }
bitfields = { path = "../bitfields" }
ahash.workspace = true

