[package]
name = "parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cranelift = "0.105"
itertools = "0.12"
thiserror = "1.0.51"
tokenizer = { path = "../tokenizer" }
