[package]
name = "resolution"
description = "resolves imports for the M language"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/Bangboom030518/M-Compiler"

[dependencies]
parser = { path = "../parser" }
lazy_static = "1.4.0"